#!/usr/bin/env bash
#
# Siamsite Bridge — one-shot installer for {{SHOP_NAME}}
# Generated by panel.siamsite.shop · key expires {{EXPIRES_AT}}
#
# What this does:
#   1. Installs MySQL 8.x on this server (if not already present)
#   2. Creates database `authme` + user with a random password
#   3. Downloads + imports your existing AuthMe data from the panel
#   4. Edits plugins/AuthMe/config.yml to point at local MySQL
#      (BCRYPT + legacyHashes: [SHA256] to keep existing players working)
#   5. Drops in the Siamsite Bridge .jar + writes its config with your token
#
# Usage:  bash setup.sh /path/to/your/mc-server
# Or:     curl -fsSL '{{SCRIPT_URL}}' | sudo bash -s -- /path/to/mc-server
#
set -euo pipefail

# ── Embedded by panel ───────────────────────────────────────────
SUB_ID="{{SUB_ID}}"
SHOP_NAME="{{SHOP_NAME}}"
BRIDGE_TOKEN="{{BRIDGE_TOKEN}}"
DUMP_URL="{{DUMP_URL}}"
BRIDGE_JAR_URL="{{BRIDGE_JAR_URL}}"
PANEL_WS="{{PANEL_WS}}"

# ── Args ────────────────────────────────────────────────────────
MC_PATH="${1:-}"
if [[ -z "$MC_PATH" ]]; then
  echo "Usage: $0 <path-to-mc-server-folder>"
  echo "Example: $0 /home/minecraft/server"
  exit 1
fi
MC_PATH="${MC_PATH%/}"

if [[ ! -d "$MC_PATH" ]]; then
  echo "✗ Folder not found: $MC_PATH"
  exit 1
fi
if [[ ! -d "$MC_PATH/plugins/AuthMe" ]]; then
  echo "✗ AuthMe plugin folder not found at $MC_PATH/plugins/AuthMe"
  echo "  Make sure your MC server has AuthMe installed and has run at least once."
  exit 1
fi

# ── sudo ────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  if command -v sudo >/dev/null; then
    echo "→ This installer needs sudo for: apt install, mysql admin commands"
    sudo -v
    SUDO="sudo"
  else
    echo "✗ Run as root or install sudo"
    exit 1
  fi
else
  SUDO=""
fi

log() { printf "\n\033[1;36m==>\033[0m %s\n" "$*"; }
ok()  { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn(){ printf "\033[1;33m!\033[0m %s\n" "$*"; }

# ── 1. Install MySQL + python3 + ruamel.yaml ────────────────────
if command -v mysql >/dev/null 2>&1; then
  ok "MySQL already installed ($(mysql --version | head -c 60)...)"
else
  log "Installing MySQL Server (apt)"
  $SUDO apt-get update -qq
  DEBIAN_FRONTEND=noninteractive $SUDO apt-get install -y -qq mysql-server
  $SUDO systemctl enable --now mysql
  ok "MySQL installed"
fi

if ! command -v python3 >/dev/null 2>&1; then
  log "Installing python3"
  DEBIAN_FRONTEND=noninteractive $SUDO apt-get install -y -qq python3 python3-pip
fi

if ! python3 -c "import ruamel.yaml" 2>/dev/null; then
  log "Installing ruamel.yaml (for safe AuthMe config edit)"
  $SUDO pip3 install --quiet --break-system-packages ruamel.yaml 2>/dev/null \
    || $SUDO pip3 install --quiet ruamel.yaml \
    || pip3 install --user --quiet ruamel.yaml
fi

# ── 2. Create DB + user ─────────────────────────────────────────
AUTHME_PASS="$(openssl rand -base64 18 | tr -d '=+/' | head -c 24)"
log "Creating database 'authme' + user 'authme'@'localhost'"
$SUDO mysql <<SQL
CREATE DATABASE IF NOT EXISTS authme CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
DROP USER IF EXISTS 'authme'@'localhost';
CREATE USER 'authme'@'localhost' IDENTIFIED BY '$AUTHME_PASS';
GRANT ALL PRIVILEGES ON authme.* TO 'authme'@'localhost';
FLUSH PRIVILEGES;
SQL
ok "Database + user ready"

# ── 3. Download + import dump ───────────────────────────────────
log "Downloading AuthMe dump from panel"
TMP_DUMP="$(mktemp /tmp/authme.XXXXXX.sql)"
trap 'rm -f "$TMP_DUMP"' EXIT
if ! curl -fsSL --max-time 120 -o "$TMP_DUMP" "$DUMP_URL"; then
  echo "✗ Dump download failed — your setup key may have expired or already been used."
  echo "  Generate a new install command from panel.siamsite.shop dashboard."
  exit 1
fi
DUMP_SIZE=$(wc -c <"$TMP_DUMP")
ok "Downloaded ${DUMP_SIZE} bytes"

log "Importing dump into local MySQL"
mysql -u authme -p"$AUTHME_PASS" authme <"$TMP_DUMP"
ROW_COUNT=$(mysql -u authme -p"$AUTHME_PASS" -N -B -e "SELECT COUNT(*) FROM authme.authme;" 2>/dev/null || echo "?")
ok "Imported ${ROW_COUNT} player rows"

# ── 4. Edit AuthMe config ───────────────────────────────────────
log "Backing up + editing plugins/AuthMe/config.yml"
AUTHME_CFG="$MC_PATH/plugins/AuthMe/config.yml"
BACKUP="${AUTHME_CFG}.bak.$(date +%s)"
cp "$AUTHME_CFG" "$BACKUP"
ok "Backup saved: $BACKUP"

python3 - "$AUTHME_CFG" "$AUTHME_PASS" <<'PYEOF'
import sys
from ruamel.yaml import YAML
path, pw = sys.argv[1], sys.argv[2]
yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
with open(path) as f:
    data = yaml.load(f)

ds = data.setdefault('DataSource', {})
ds['backend'] = 'MYSQL'
ds['caching'] = False
ds['mySQLHost'] = '127.0.0.1'
ds['mySQLPort'] = '3306'
ds['mySQLUseSSL'] = False
ds['mySQLCheckServerCertificate'] = False
ds['mySQLAllowPublicKeyRetrieval'] = True
ds['mySQLUsername'] = 'authme'
ds['mySQLPassword'] = pw
ds['mySQLDatabase'] = 'authme'
ds['mySQLTablename'] = 'authme'
ds['poolSize'] = 10
ds['maxLifetime'] = 1770

sec = data.setdefault('settings', {}).setdefault('security', {})
sec['passwordHash'] = 'BCRYPT'
legacy = sec.get('legacyHashes') or []
if isinstance(legacy, str):
    legacy = [legacy]
if 'SHA256' not in legacy:
    legacy.append('SHA256')
sec['legacyHashes'] = legacy

with open(path, 'w') as f:
    yaml.dump(data, f)
print(f"AuthMe config updated — DataSource → 127.0.0.1, passwordHash=BCRYPT, legacyHashes={legacy}")
PYEOF
ok "AuthMe config patched"

# ── 5. Install Bridge plugin + write its config ─────────────────
log "Downloading Siamsite Bridge plugin"
curl -fsSL --max-time 60 -o "$MC_PATH/plugins/siamsite-bridge.jar" "$BRIDGE_JAR_URL"
ok "Bridge jar installed: $MC_PATH/plugins/siamsite-bridge.jar"

mkdir -p "$MC_PATH/plugins/SiamsiteBridge"
cat > "$MC_PATH/plugins/SiamsiteBridge/config.yml" <<YAML
# Generated by panel.siamsite.shop installer for $SHOP_NAME
# Edit panel.token only — auto AuthMe means we read from plugins/AuthMe/config.yml
panel:
  url: $PANEL_WS
  token: "$BRIDGE_TOKEN"

authme:
  auto: true
  table: authme

bridge:
  connection_pool_size: 4
  worker_threads: 4
  reconnect_initial_ms: 1000
  reconnect_max_ms: 60000
  max_inflight: 256
YAML
ok "Bridge config written"

# ── Done ────────────────────────────────────────────────────────
cat <<DONE

════════════════════════════════════════════════════════════════
  ✓ Setup สำเร็จ — $SHOP_NAME
════════════════════════════════════════════════════════════════

  AuthMe MySQL password : $AUTHME_PASS
  AuthMe config backup  : $BACKUP
  Bridge token prefix   : ${BRIDGE_TOKEN:0:8}...
  Player rows imported  : $ROW_COUNT

  ขั้นตอนสุดท้าย:
    1. รีสตาร์ทเซิร์ฟเวอร์ Minecraft ของคุณ
    2. รอ ~5 วินาที แล้วเช็คหน้า Dashboard → Bridge
       สถานะจะเปลี่ยนเป็น "ออนไลน์" สีเขียว
    3. ลอง /login ในเกมด้วย account เก่า — ต้องผ่าน

  ถ้ามีปัญหา: พิมพ์ /siamsite-bridge status ในคอนโซลเซิร์ฟ
  หรือทักแอดมินที่แฟนเพจ facebook.com/siamsitestore

════════════════════════════════════════════════════════════════
DONE
