# Siamsite Bridge - one-shot installer for {{SHOP_NAME}}
# Generated by panel.siamsite.shop * key expires {{EXPIRES_AT}}
#
# What this does:
#   1. Installs MySQL 8.x via winget (if not already present)
#   2. Creates database 'authme' + user with a random password
#   3. Downloads + imports your existing AuthMe data from the panel
#   4. Edits plugins/AuthMe/config.yml to point at local MySQL
#      (BCRYPT + legacyHashes: [SHA256] to keep existing players working)
#   5. Drops in the Siamsite Bridge .jar + writes its config with your token
#
# Usage (run PowerShell as Administrator):
#   .\setup.ps1 -McPath "C:\path\to\mc-server"
# Or one-liner:
#   iwr '{{SCRIPT_URL}}' | iex; Install-SiamsiteBridge -McPath "C:\..."
#
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$McPath
)
$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'

# -- Embedded by panel --
$SubId        = '{{SUB_ID}}'
$ShopName     = '{{SHOP_NAME}}'
$BridgeToken  = '{{BRIDGE_TOKEN}}'
$DumpUrl      = '{{DUMP_URL}}'
$BridgeJarUrl = '{{BRIDGE_JAR_URL}}'
$PanelWs      = '{{PANEL_WS}}'

function Log  { param($m) Write-Host "`n==> $m" -ForegroundColor Cyan }
function Ok   { param($m) Write-Host "✓ $m"      -ForegroundColor Green }
function Warn { param($m) Write-Host "! $m"      -ForegroundColor Yellow }
function Die  { param($m) Write-Host "✗ $m"      -ForegroundColor Red; exit 1 }

# -- Admin check --
$IsAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $IsAdmin) { Die "Run PowerShell as Administrator (right-click -> Run as Administrator)" }

# -- Validate McPath --
$McPath = $McPath.TrimEnd('\','/')
if (-not (Test-Path $McPath))                          { Die "Folder not found: $McPath" }
if (-not (Test-Path "$McPath\plugins\AuthMe"))         { Die "AuthMe plugin folder not found at $McPath\plugins\AuthMe" }

# -- 1. Install MySQL + Python --
function Refresh-Path {
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' +
                [System.Environment]::GetEnvironmentVariable('Path','User')
}

if (Get-Command mysql -ErrorAction SilentlyContinue) {
    Ok "MySQL already installed"
} else {
    Log "Installing MySQL Server via winget"
    if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
        Die "winget not found. Please install MySQL 8.x manually from https://dev.mysql.com/downloads/installer/ then re-run this script."
    }
    winget install --id Oracle.MySQL --silent --accept-package-agreements --accept-source-agreements | Out-Null
    Refresh-Path
    if (-not (Get-Command mysql -ErrorAction SilentlyContinue)) {
        Die "MySQL install completed but 'mysql' is not on PATH. Open a NEW PowerShell as Admin and re-run."
    }
    Ok "MySQL installed"
}

if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
    Log "Installing Python via winget"
    winget install --id Python.Python.3.12 --silent --accept-package-agreements --accept-source-agreements | Out-Null
    Refresh-Path
}
python -m pip install --quiet --disable-pip-version-check ruamel.yaml | Out-Null
Ok "Python + ruamel.yaml ready"

# -- 2. Create DB + user --
$AuthmePass = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 24 | ForEach-Object { [char]$_ })

$RootPwSec = Read-Host -Prompt "ใส่ MySQL root password (ตอนติดตั้ง MySQL ที่ตั้งไว้)" -AsSecureString
$RootPw    = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($RootPwSec))

Log "Creating database 'authme' + user 'authme'@'localhost'"
$Sql = @"
CREATE DATABASE IF NOT EXISTS authme CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
DROP USER IF EXISTS 'authme'@'localhost';
CREATE USER 'authme'@'localhost' IDENTIFIED BY '$AuthmePass';
GRANT ALL PRIVILEGES ON authme.* TO 'authme'@'localhost';
FLUSH PRIVILEGES;
"@
$Sql | mysql -u root "-p$RootPw"
if ($LASTEXITCODE -ne 0) { Die "Could not create database. Wrong root password?" }
Ok "Database + user ready"

# -- 3. Download + import dump --
Log "Downloading AuthMe dump from panel"
$TmpDump = Join-Path $env:TEMP "authme-$(Get-Random).sql"
try {
    Invoke-WebRequest -Uri $DumpUrl -OutFile $TmpDump -UseBasicParsing -TimeoutSec 120
} catch {
    Die "Dump download failed - your setup key may have expired or been used. Generate a new install command from the panel."
}
$DumpSize = (Get-Item $TmpDump).Length
Ok "Downloaded $DumpSize bytes"

Log "Importing dump into local MySQL"
Get-Content $TmpDump -Raw | mysql -u authme "-p$AuthmePass" authme
if ($LASTEXITCODE -ne 0) { Die "Dump import failed" }
Remove-Item $TmpDump -Force
$RowCount = (mysql -u authme "-p$AuthmePass" -N -B -e "SELECT COUNT(*) FROM authme.authme;" 2>$null).Trim()
Ok "Imported $RowCount player rows"

# -- 4. Edit AuthMe config --
Log "Backing up + editing plugins\AuthMe\config.yml"
$AuthmeCfg = "$McPath\plugins\AuthMe\config.yml"
$Backup    = "$AuthmeCfg.bak.$(Get-Date -Format yyyyMMddHHmmss)"
Copy-Item $AuthmeCfg $Backup
Ok "Backup saved: $Backup"

$PyScript = @"
import sys
from ruamel.yaml import YAML
path, pw = sys.argv[1], sys.argv[2]
yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
with open(path) as f:
    data = yaml.load(f)
ds = data.setdefault('DataSource', {})
ds['backend'] = 'MYSQL'
ds['caching'] = False
ds['mySQLHost'] = '127.0.0.1'
ds['mySQLPort'] = '3306'
ds['mySQLUseSSL'] = False
ds['mySQLCheckServerCertificate'] = False
ds['mySQLAllowPublicKeyRetrieval'] = True
ds['mySQLUsername'] = 'authme'
ds['mySQLPassword'] = pw
ds['mySQLDatabase'] = 'authme'
ds['mySQLTablename'] = 'authme'
ds['poolSize'] = 10
ds['maxLifetime'] = 1770
sec = data.setdefault('settings', {}).setdefault('security', {})
sec['passwordHash'] = 'BCRYPT'
legacy = sec.get('legacyHashes') or []
if isinstance(legacy, str): legacy = [legacy]
if 'SHA256' not in legacy: legacy.append('SHA256')
sec['legacyHashes'] = legacy
with open(path, 'w') as f:
    yaml.dump(data, f)
print('AuthMe config updated:', legacy)
"@
$PyFile = Join-Path $env:TEMP "edit-authme-$(Get-Random).py"
Set-Content -Path $PyFile -Value $PyScript -Encoding UTF8
python $PyFile $AuthmeCfg $AuthmePass
Remove-Item $PyFile -Force
Ok "AuthMe config patched"

# -- 5. Install Bridge plugin + config --
Log "Downloading Siamsite Bridge plugin"
Invoke-WebRequest -Uri $BridgeJarUrl -OutFile "$McPath\plugins\siamsite-bridge.jar" -UseBasicParsing
Ok "Bridge jar installed"

$BridgeCfgDir = "$McPath\plugins\SiamsiteBridge"
New-Item -ItemType Directory -Force -Path $BridgeCfgDir | Out-Null
@"
# Generated by panel.siamsite.shop installer for $ShopName
panel:
  url: $PanelWs
  token: "$BridgeToken"

authme:
  auto: true
  table: authme

bridge:
  connection_pool_size: 4
  worker_threads: 4
  reconnect_initial_ms: 1000
  reconnect_max_ms: 60000
  max_inflight: 256
"@ | Set-Content -Path "$BridgeCfgDir\config.yml" -Encoding UTF8
Ok "Bridge config written"

# -- Done --
Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  ✓ Setup สำเร็จ — $ShopName"                                     -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "  AuthMe MySQL password : $AuthmePass"
Write-Host "  AuthMe config backup  : $Backup"
Write-Host "  Bridge token prefix   : $($BridgeToken.Substring(0,8))..."
Write-Host "  Player rows imported  : $RowCount"
Write-Host ""
Write-Host "  ขั้นตอนสุดท้าย:"
Write-Host "    1. รีสตาร์ทเซิร์ฟเวอร์ Minecraft ของคุณ"
Write-Host "    2. รอ ~5 วินาที แล้วเช็คหน้า Dashboard -> Bridge"
Write-Host "       สถานะจะเปลี่ยนเป็น `"ออนไลน์`" สีเขียว"
Write-Host "    3. ลอง /login ในเกมด้วย account เก่า — ต้องผ่าน"
Write-Host ""
Write-Host "  ถ้ามีปัญหา: พิมพ์ /siamsite-bridge status ในคอนโซลเซิร์ฟ"
Write-Host "  หรือทักแอดมินที่แฟนเพจ facebook.com/siamsitestore"
Write-Host ""
